### ISSUE TITLE
Dropdown box with more information for foreign stocks

### ISSUE THREAD

**Issue by Manuito83** [Manuito83/torn-pda#10]
This suggestion was made by Phillip_J_Fry (Discord)

On the foreign stock section, when you click on an item, it should drop down like in the game and give a better description of all the numbers and what not that are on the items bar.

Also add in the total cost that you should bring on the trip

Maybe add in the mug protection % and how much you should bring in case you get mugged and still have enough to get you max capacity, in the drop down box

**Comment by Kivou-2000607** [comment]
I compute monthly and weekly tendencies / item and store prices over a month on YATA.
I could give tpda an entry to that part of the db if you're interested.

**Comment by Manuito83** [comment]
Hey Kivou thanks a lot for that, sound good! I'll let you know when I can start with this feature (it will take some time) and we can see how to perform the implementation. Thanks again for the help.

**Comment by Kivou-2000607** [comment]
It's alright.
The more you do the less people ask me for a mobile friendly YATA ^^

**Comment by Manuito83** [comment]
Implemented in v2.2.0
