### ISSUE TITLE
Travel stocks not working

### ISSUE THREAD

**Issue by phil8ter** [Manuito83/torn-pda#105]
I can't view items overseas. Keeps saying oops.

**Comment by DeKleineKobini** [comment]
This is not a Torn PDA issue. YATA is currently down, Torn PDA gets the travel stocks from there.

**Comment by Manuito83** [comment]
Correct, there are multiple services that depend on YATA and they are currently facing some issues with server load. Hopefully this should be resolved in the next few days.

**Comment by phil8ter** [comment]
Thank you. 
Yata is up and running again. It is working
