### ISSUE TITLE
Travel page visual improvements

### ISSUE THREAD

**Issue by Manuito83** [Manuito83/torn-pda#11]
This suggestion was made by Phillip_J_Fry (Discord)

Remove the Travel notifications and move them to a separate button like the foreign stock button on the opposite side with the default bell icon.

Then add a travel time bar to the main travel page

**Comment by pjfry2184575** [comment]
Also if you could put a travel bar to appear when on the profile page in the status section

**Comment by Manuito83** [comment]
> Also if you could put a travel bar to appear when on the profile page in the status section

Nice idea. That can be done easily. Thanks.

**Comment by Manuito83** [comment]
Travel bar has been implemented in 6025540e965dca3dd613cabeba870eae93aa597a

**Comment by Manuito83** [comment]
Fully implemented in v1.7.0
