### ISSUE TITLE
Feature Request: Crimes under basic info

### ISSUE THREAD

**Issue by SerkanVaroglu** [Manuito83/torn-pda#110]
Loving the app! Is it possible to add crime counts on basic info section?

**Comment by Manuito83** [comment]
Thank you! What kind of crime count, could you specify? We are going to add a full Awards section very shortly. Could you have a look at it in a few days? Perhaps we could include the pinned awards to the Profile section.

**Comment by SerkanVaroglu** [comment]
Criminal Offences on homepage that shows the count for each type like fraud, theft etc. Awards might solve it to be honest so I will try that when it comes out ;)
