### ISSUE TITLE
Question: Custom userscripts

### ISSUE THREAD

**Issue by jgonyea** [Manuito83/torn-pda#128]
I'd imagine that iOS wouldn't allow this feature, but would it be possible to load my own userscripts into torn-pda on Android?  I have some really helpful ones I use on the desktop that I'd love to use on my mobile as well.

Thanks in advance either way

**Comment by Manuito83** [comment]
Hi. Yes, this is possible, both on iOS and Android, it's something I've thought for a future development, but it should not be a problem technically speaking. 

There are a few things to take into consideration, though (e.g. for the time being, scripts should be plain javascript, there is no jquery allowed). Also, we'd need to figure out what variables should be made available from the Dart environment for the scripts.

What we are doing for the time being, is hard coding the most common/requested features in the app (also in javascript). If you'd be interesting in helping, or have any ideas, please let me know, we have a group in Discord and any help with this is appreciated. I think this is a pending subject where the app could improve a lot if we can port the existing scripts/ideas into it.
