### ISSUE TITLE
App freezes when opening google sheets

### ISSUE THREAD

**Issue by cryosis7** [Manuito83/torn-pda#131]
When opening google sheets in the app browser (for example, a link in a mail to a chain watch schedule which is a sheets document) everything freezes and stops responding

**Comment by Manuito83** [comment]
Thank you. I can't replicate locally in the new beta. I would appreciate if you can contact me in Discord to see if we can test the new version as it might be solved already.

**Comment by Manuito83** [comment]
@cryosis7 is this still happening?

**Comment by cryosis7** [comment]
I’ve stopped playing Torn sorry – I don’t know
