### ISSUE TITLE
inappwebview.dev showcase page

### ISSUE THREAD

**Issue by pichillilorenzo** [Manuito83/torn-pda#136]
Hi @Manuito83, if you want, you could submit your app to the new official website of `flutter_inappwebview` plugin (that is [inappwebview.dev](https://inappwebview.dev/)), using the  [Submit App Page](https://inappwebview.dev/submit-app/).

After you followed the instructions, It will add your app into the [Showcase Page](https://inappwebview.dev/showcase/), which contains an open list of apps built with Flutter and Flutter InAppWebView.

If you don't want, just ignore this 😄

**Comment by Manuito83** [comment]
Absolutely, will do when I have a minute, I'm a fan! Good job with version 5, what a comeback! @pichillilorenzo

**Comment by pichillilorenzo** [comment]
Thank you, Manuel!! I appreciated that a lot! 😄 👍

**Comment by pichillilorenzo** [comment]
Also, if you want, I can add it by myself using info, description and screenshots from the official stores 😄

**Comment by Manuito83** [comment]
Hi Lorenzo. I'm sorry I've been unable to do it, I've been very busy, but I should have some time this weekend. 

If you'd like to go ahead, yep, absolutely, I have not problem if you can do it with the what's available in the official stores (which are the images I was going to submit). Let me know! :)

**Comment by pichillilorenzo** [comment]
I tried but the App logo and App screenshots have low resolution on Google and Apple stores.
If you can, you can drag and drop here to this issue up to 8 App screenshots and the App logo with high resolution!
I will take them from here (the GitHub CDN) 👍

**Comment by Manuito83** [comment]
Absolutely, thanks a lot!

I'm uploading a mix of them. If you'd like to have more just related to flutter_inappwebview let me know. There is also one showing how user's will be adding custom user scripts (which was made possible very recently).

By the way: the new website and the documentation look awesome, congratulations!

![screenshot (1)](https://user-images.githubusercontent.com/4816367/112354194-bbfbf200-8ccc-11eb-8885-dacd424c1c38.png)
![screenshot (2)](https://user-images.githubusercontent.com/4816367/112354197-bd2d1f00-8ccc-11eb-87e4-eeaab10d2fcc.png)
![screenshot (3)](https://user-images.githubusercontent.com/4816367/112354203-bd2d1f00-8ccc-11eb-87a4-3c4f8fdd9557.png)
![screenshot (4)](https://user-images.githubusercontent.com/4816367/112354204-bd2d1f00-8ccc-11eb-9aa8-1ebe5dd62c06.png)
![screenshot (5)](https://user-images.githubusercontent.com/4816367/112354206-bdc5b580-8ccc-11eb-88f1-5aac35f765c3.png)
![screenshot (6)](https://user-images.githubusercontent.com/4816367/112354207-bdc5b580-8ccc-11eb-9486-6e40522b085f.png)
![screenshot (7)](https://user-images.githubusercontent.com/4816367/112354210-be5e4c00-8ccc-11eb-8973-afcecc52d5dd.png)
![torn_pda](https://user-images.githubusercontent.com/4816367/112354212-be5e4c00-8ccc-11eb-8f72-dca0fb047233.png)

**Comment by pichillilorenzo** [comment]
Thanks to you! 👍  That's perfect! I will post here the link

**Comment by pichillilorenzo** [comment]
Here is the link: https://inappwebview.dev/flutter-app/torn-pda/.

If you need to change something, you can make a pull request to the [flutter_inappwebview-showcase-data](https://github.com/pichillilorenzo/flutter_inappwebview-showcase-data/blob/master/data.json) repository, which contains all the data in JSON format inside the data.json file 😄

**Comment by Manuito83** [comment]
Looks great, thanks a lot!
