### ISSUE TITLE
Warning when rental is about to end.

### ISSUE THREAD

**Issue by kruug** [Manuito83/torn-pda#137]
Torn sends a notification roughly 12 hours before a rental agreement is going to end.

Since “[property][rented][days_left]” exists in the API, can a configurable warning be implemented into the PDA?

Personally, is like a 2-day warning.  That gives me time to reach out to the property owner for them to send out another agreement.

**Comment by kruug** [comment]
https://api.torn.com/property/?selections=property&key=

The upkeep doesn't seem to be properly calculated, but this does seem like it could be its own section as well in the “Profile” tab.

**Comment by Manuito83** [comment]
Hi @kruug, thanks for the request. This is related to #42.

Would it be enough if we put the information in the MISC card, in Profile, or does it have to be an alert?

**Comment by kruug** [comment]
Personally, I’d prefer the alert over the information on a card.  But having the information available anywhere in the app would be greatly appreciated.

**Comment by Manuito83** [comment]
As I'm quite advance with v2.3.0, I'll implement a check in the Profile section first (< 7 days), for all rented properties.

Then, in the future, we can see about implementing an alert.

I hope this is fine!

![qemu-system-x86_64_PfEwEW1MGL](https://user-images.githubusercontent.com/4816367/111395768-eb53a300-86bd-11eb-8588-0324b429c893.png)

**Comment by kruug** [comment]
That looks great!  Thank you for the addition!

Understood about where you are in the development cycle of the next release.

**Comment by Manuito83** [comment]
Closing this as it's included in v2.3.0. If needed we could reopen it in the future for alerts (if really necessary!)
