### ISSUE TITLE
Feature request: Warn me if I'm about to forget my daily refill(s)

### ISSUE THREAD

**Issue by smikula** [Manuito83/torn-pda#139]
So many days the TCT day change comes along and I forgot to do my energy refill.  TornPDA should be able to solve this!  Add an option to have a reminder to use your refill X hours before the day ends, if you haven't already.  (Same for nerve/casino tokens.)

**Comment by Manuito83** [comment]
Thanks @smikula 

This is all the information we need, correct?

![image](https://user-images.githubusercontent.com/4816367/115547145-39079080-a2a6-11eb-91e6-003be93dbdd3.png)

**Comment by smikula** [comment]
I think that should do it, yeah.  (Well, that and the current time in TCT.)

**Comment by Manuito83** [comment]
Firing at 22:00 TCT would do?

**Comment by smikula** [comment]
Sounds good to me!

**Comment by Manuito83** [comment]
Released with v2.3.4
