### ISSUE TITLE
Shortcut Grid Improvement

### ISSUE THREAD

**Issue by zwu513** [Manuito83/torn-pda#146]
The shortcut grid in the profile tab does not behave the way I expected it to. The individual buttons are far too small to tap on accurately. They are about 0.65 cm on a 6.2-inch 3200x1440p phone. I personally would prefer the buttons to be around 1 cm, so in a 4 or 5 wide grid on my phone. (Sorry for the terrible units) They are also black icons on dark gray in dark mode. 
![Screenshot_20210723-230414](https://user-images.githubusercontent.com/32444398/126859252-914bf7b4-9623-4166-8e09-50a938f6fd46.png)

**Comment by Manuito83** [comment]
Hi, thank you.

I'll correct the color in dark mode.

Regarding the size, this was intentional (we have the opposite issue in narrower screens where users still want to have as many icons as possible). If you would like to have larger icons, would it not make sense to use the "text + icon" presentation option for the shortcut tiles?

**Comment by zwu513** [comment]
That does work. I didn't realize that chnaged the size too. Also, a few unrelated bugs. The foreign stock check does not as it seems travel times are broken. Some animation, like the foreign stock and keyboard popup are slow and choppy. Also, can total capacity be automatically detected?

**Comment by Manuito83** [comment]
What do you mean with travel times are broken?

I don't believe total capacity is in the API, so it can't be automated. Also, for certain specific jobs/perks, the real total capacity is higher than what's shown when you arrive to a certain country. Could be difficult to automate without errors, even by parsing the web.

**Comment by zwu513** [comment]
Sorry, I meant restock times. Items with no data are being listed fairly high. Like the dual 92g. For the travel capacity, could you parse the personal perks under the home page?

**Comment by Manuito83** [comment]
The information for foreign stocks come from YATA's database. Any item that has appeared in a country in the last few days remain listed for some time, as an indication that it can appear again. Also, restock times have a 'reliability' indicator, based on how precise the restock times are, that should be a good indicator of if can be trusted; it's normally only flowers, and sometimes plushies, the ones with a high/medium reliability. 

Parsing the personal perks under the home page requires the user to enter that section, and an extra call every time Torn opens (just in case travel capacity has changed). Is it not easy, and more performing, if the user just sets it once manually?

Thanks again!
