### ISSUE TITLE
Points building double click

### ISSUE THREAD

**Issue by robgom** [Manuito83/torn-pda#147]
Hi, per bug report on Torn (I'm still not sure where's the issue):

Hi all,
I am *not sure* if this is an issue with Torn PDA or Torn, but searched Torn PDA repo a bit and didn't find anything relevant, so I guess it might be more general (though I couldn't find any similar bug report).

Problem: when entering Points Building section and clicking on any widget for the first time, it is expanded, then collapsed. Second click is ok.
It's annoying.

Reproducible: always
Steps to reproduce:
1. Go to points building section (I do it directly, don't know if it matters)
2. Click on Energy or Nerve or Casino tokens (have checked those, haven't checked others)
3. The app displays "are you sure to spend[...]" message, then collapses view, like it thinks I clicked the widget for the second time
4. I click the widget for the second time and it is normal this time.

If I exit to main app section and enter Points Building again, it appears again.

I don't have torn app installed, so can't check on that.

This is the only place I have found such behaviour.

The issue occurs when I use in-app browser. The issue doesn't occur when I use external browser. (Changed from Torn PDA settings).

Please let me know if you need more information.

Original bug report:
https://www.torn.com/forums.php#/p=threads&f=19&t=16237392&b=0&a=0&start=0&to=21703482

Regards

**Comment by Manuito83** [comment]
Hi. 

Thanks for letting me know. I can reproduce it if I use a shortcut, but not if I browse from the city. 

But there is another weird behaviour related to this that I'll post in the official forum.

**Comment by Manuito83** [comment]
This has been confirmed to happen in the official app as well, so it doesn't look like a Torn PDA issue.

As a temporary fix, I can see it only happens if the URL is accessed directly (for example from a shortcut), but not if we browse to it from another URL.

**Comment by Manuito83** [comment]
I'm closing this after it was replicated at least twice by Torn staff and confirmed a bug in Torn (not just Torn PDA).

https://www.torn.com/forums.php#/p=threads&f=19&t=16237392&b=0&a=0&start=0&to=21717762

Thanks for the help!
