### ISSUE TITLE
Refreshing a page in iOS version leads to multiple executions of a custom scripts

### ISSUE THREAD

**Issue by JJins** [Manuito83/torn-pda#151]
It seems some scripts will be called increasing times by refreshing the page. Such as this script: https://github.com/Manuito83/torn-pda/blob/master/userscripts/Company%20Activity%20(Torn%20PDA).js. This bug only exists in the iOS version of pda. It does not appear on the iOS Alook app or on the android pda.

**Comment by Manuito83** [comment]
Hey, thanks for that, sorry for the late reply.

This script has been coded by an external developer, but it should be straightforward to ensure that it's only executed once. I'll add this to the list for a next version (or feel free to submit a PR!).

Thanks!

**Comment by Manuito83** [comment]
This should be fixed (this particular script) in v2.6.1.
