### ISSUE TITLE
Auto price set script

### ISSUE THREAD

**Issue by Acidicloki** [Manuito83/torn-pda#164]
The bazaar auto price set script no longer works

**Comment by Manuito83** [comment]
Thanks. Have a look at the forum, please, there is a quick fix for this: https://www.torn.com/forums.php#/p=threads&f=67&t=16163503&b=0&a=0&start=820&to=22147962

This is also fixed here: b797debc756608fbed851878567d7a974c4f5b00 for v2.6.5
