### ISSUE TITLE
Travel: Earliest return inaccurate using 10* LS special

### ISSUE THREAD

**Issue by gl1tchh** [Manuito83/torn-pda#173]
When travelling using the LS 10* bonus (free BCT), the "earliest return" is still calculating based on airstrip times.

Screenshot:

![Screenshot_20220327-203154](https://user-images.githubusercontent.com/4974010/160296669-28f9b563-09d9-4e7d-839a-f8ac94bfcfbd.jpg)

With a travel time of 1h 21m, earliest return should be ~23:09 LT, 00:58 would be a travel time of 3h 10m (airstrip)

**Comment by Manuito83** [comment]
Torn PDA can't see what ticket you are using (except maybe assume the type in this particular case...?), but there is an option to change your ticket type in the foreign stock page (at the top, settings icon). Have you tried to use that one?

**Comment by gl1tchh** [comment]
> Torn PDA can't see what ticket you are using (except maybe assume the type in this particular case...?), but there is an option to change your ticket type in the foreign stock page (at the top, settings icon). Have you tried to use that one?

I see it now, will confirm if that updates it when I fly again. I didn't think to look there as I was under the impression those settings were related to profit calculation, but I see in the description it says it affects all time based travel calculations. Thanks!
