### ISSUE TITLE
Cannot export lists to YATA (but importing works)

### ISSUE THREAD

**Issue by hirunatan** [Manuito83/torn-pda#178]
I have connected my TornPDA to my account in YATA. I use different API keys for each service, so I put them all in the settings / Alternative API keys section.

When in the Chain screen, with the YATA button, I can Import a list of targets. But if I press "export to YATA", it says me "There was an error exporting!", with no further information or way of knowing what is the problem.

Any clue? Any test I could do or thing I could try changing? Thanks.

**Comment by Manuito83** [comment]
Hi. Could you PM me in Discord your targets list (exported with the backup functionality) so that I can try? Otherwise, perhaps we could try a few things in beta if you want to sign up.

**Comment by hirunatan** [comment]
Fixed for me, thanks!
