### ISSUE TITLE
Restock notifications only when you are in that country

### ISSUE THREAD

**Issue by CTJoriginal** [Manuito83/torn-pda#179]
It would be great if restock notifications would only be sent when you are in specific country as it's kinda annoying to recieve these while you dont need it.
I dont know if this is already a thing since it says "auto" but if it is, it doesnt work for me.

**Comment by JohnnyDeeee** [comment]
Also interested in this. I keep enabling these notifications once i see the stock is 0 when i land. If i then receive a stock notification i first turn it off and then buy and fly back.

It would be great if i get an option for notifying only once or only notify if i am in the specific country.

**Comment by Manuito83** [comment]
Added in v3.4.3
