### ISSUE TITLE
Cannot logon via Google on iOS 16.1.2

### ISSUE THREAD

**Issue by AlkatarPL** [Manuito83/torn-pda#183]
Cannot log on to account via TornPDA with Google Signon on iOS 16.1.2. I can, sometime, open the Google signon and select account but page goes white and does not procedd. If I signon in Firefox and the switch to TornPDA I can proceed to Torn via App.

**Comment by Manuito83** [comment]
Thanks. I'm looking to have this fixed with the next version.

**Comment by AlkatarPL** [comment]
awesome :) thanks

**Comment by Manuito83** [comment]
Could you confirm if it works? v2.9.5

**Comment by AlkatarPL** [comment]
Like a charm! ThanksSent from my iPhoneOn 3 Feb 2023, at 15:40, Manuito ***@***.***> wrote:﻿
Could you confirm if it works? v2.9.5
