### ISSUE TITLE
Minor display bugs

### ISSUE THREAD

**Issue by Dictynna-PHA** [Manuito83/torn-pda#185]
Noticed a few display bugs in the latest version, quite minor but just so you’re aware. 
iPhone iOS 16.3 pda version 2.9.4 (278)

When going from the city map to some other pages (city quicklinks, raceway and crimes) the top “items found” display stays active (see screenshots) this does it on iPhone and on iPad (but only in portrait, landscape acts as expected)

![9B080CCF-CE4F-41FA-A6F3-B0E61C0F39F6](https://user-images.githubusercontent.com/82800964/216619635-e29c9f73-5051-4bdd-8999-7a2ff038f9d8.png)

Also occasionally have crimes results shifted to the right at random times (I can’t reproduce this with any regularity as it appears random)
![8B711B57-F987-4F43-98FA-0D2EEF61582B](https://user-images.githubusercontent.com/82800964/216619705-ae1e7ba9-04a6-49e3-aabe-4b4b4affb981.png)
![5E66B8CC-9035-439E-9BED-A9113C51310F](https://user-images.githubusercontent.com/82800964/216619706-6fd413b9-c299-4e95-9db1-19a9175fbefc.png)

**Comment by Manuito83** [comment]
Thank you! I'll have a look. City Quick Links is intentional, but the others are not.

**Comment by Dictynna-PHA** [comment]
> intentional

NP. Clearing browser cache has cleared the city finds error btw so it looks like just a cached page problem. (sorry should have tried that first!)

**Comment by Manuito83** [comment]
There's something going on with the widget not disappearing, though, as I can replicate it locally. I'll investigate. Thanks again!
