### ISSUE TITLE
Spies from TornStats

### ISSUE THREAD

**Issue by Arsura-Havenglow** [Manuito83/torn-pda#203]
Spies submitted on Tornstats via API are not showing up on profiles.

The spies show up on the update list from TornStats but they show up as the tornid and they aren’t show in profiles or the chaining/war page.

**Comment by Kwack-Kwack** [comment]
Can I confirm what version you're on (v3.2.5 is the latest stable version)? Also what OS you're currently on?

My TS spies are working fine as far as I can tell on v3.2.5, including new ones I added about a week ago. Have you updated your spies (settings --> update spies, about halfway down? It may take a while to update)?

**Comment by Kwack-Kwack** [comment]
Ah perfect, I've reproduced this. You're absolutely correct, it's currently searching up spies by player name rather than player ID. I'll look into this now, good catch!

**Comment by Kwack-Kwack** [comment]
Fixed in #206 and now merged, thanks for the bug report!
