### ISSUE TITLE
Enable retaliation alerts without enabling notifications

### ISSUE THREAD

**Issue by danielbarnes175** [Manuito83/torn-pda#225]
**Summary**

Currently, for retaliation alerts to work, at least one user in your faction with faction API permissions has to have the alert enabled. After they have enabled it, then users without faction API access are able to use it. This, however, can be a problem if the user with faction API permissions wants to let other faction members use the alert, but they themselves do not want these notifications.

**Request**

* Add a toggle for those with faction API permissions to be able to "enable" retaliation alerts without actually turning on the alert on their device.

Currently the UI looks like this:
![image](https://github.com/Manuito83/torn-pda/assets/31489642/8ded7702-11c4-4a2f-a267-1f1246429277)
We can have two options:
* **Retaliation**
  Description: Get notified whenever it is possible to initiate a retaliation attack. Someone with Faction API access in your faction must have retaliation for others enabled.
* **Retaliation (For Others)**
  Description: Allow faction members without Faction API access to use retaliation alerts. This will not have any effect if you do not have faction API access

Then just also make it so that if you turn on **Retaliation** then it will also check the box for **Retaliation (For Others)**

**Comment by Manuito83** [comment]
Thanks!

**Comment by danielbarnes175** [comment]
Would this additional toggle only show for users with faction API permissions? There’s nothing that says it won’t have any effect if people don’t have faction API access, and I think that’s important.

I also think `…might be used by the server to send notifications about retaliations to all other members` can be more succinct with `…send retaliation notifications to faction members` but this feels more of a personal preference of `faction members` over `all other members`

There’s also a couple minor typos `Relation alerts` -> `Retaliation alerts`

Other than that, I think it’s good!

**Comment by Manuito83** [comment]
Thanks again!

> _Would this additional toggle only show for users with faction API permissions? There’s nothing that says it won’t have any effect if people don’t have faction API access, and I think that’s important._

Yes, this option will only appear if Torn PDA detects that the user has got Faction API privileges.

**Comment by Manuito83** [comment]
This has been merged to the beta branch and will make it to v3.3.0.

Firebase functions have already been updated.

**Comment by danielbarnes175** [comment]
Thanks for quickly addressing this!
