### ISSUE TITLE
City - Map View

### ISSUE THREAD

**Issue by gitrepohub** [Manuito83/torn-pda#296]
iOS 18.1.1
iPhone 14 Pro
V 3.6.1 (465)

when I tap on the  city then tap on map I can’t go back to quick links as the map view takes the whole screen space 

please fix

thanks
![image](https://github.com/user-attachments/assets/84efa772-8e7e-49ba-91aa-caa78d87427b)

**Comment by Kwack-Kwack** [comment]
This is a torn feature - you've opened the map in fullscreen at some point. 

Tap the two diagonal arrows button top-right (on the map, below the magnifying glass) to exit torn's fullscreen mode for the map. You may have to double tap the button from memory...

**Comment by gitrepohub** [comment]
Ah so true 
Thanks
